// <auto-generated />
using MediaCatalog.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaCatalog.DataAccess.Migrations
{
    [DbContext(typeof(MediaCatalogDbContext))]
    [Migration("20260123114954_AddMediaFileHasTag")]
    partial class AddMediaFileHasTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MediaCatalog.Entities.Entities.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.MediaFileHasTag", b =>
                {
                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaFileHasTags");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagTypeId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.TagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagTypes");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.MediaFile", b =>
                {
                    b.HasOne("MediaCatalog.Entities.Entities.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.MediaFileHasTag", b =>
                {
                    b.HasOne("MediaCatalog.Entities.Entities.MediaFile", "MediaFile")
                        .WithMany("MediaFileHasTags")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaCatalog.Entities.Entities.Tag", "Tag")
                        .WithMany("MediaFileHasTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.Tag", b =>
                {
                    b.HasOne("MediaCatalog.Entities.Entities.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.Folder", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.MediaFile", b =>
                {
                    b.Navigation("MediaFileHasTags");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.Tag", b =>
                {
                    b.Navigation("MediaFileHasTags");
                });

            modelBuilder.Entity("MediaCatalog.Entities.Entities.TagType", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
